package consts

const (
	DB_DRIVER_NAME = "DRIVER_NAME"
	DB_USER        = "ENTIFY_REGISTRY_DB_USER"
	DB_PASSWORD    = "ENTIFY_REGISTRY_DB_PASSWORD"
	DB_HOST        = "ENTIFY_REGISTRY_DB_HOST"
	DB_PORT        = "ENTIFY_REGISTRY_DB_PORT"
	DB_SCHEMA      = "ENTIFY_REGISTRY_DB_SCHEMA"
	INSTALLED      = "ENTIFY_REGISTRY_INSTALLED"
)
