package consts

const (
	CONFIG_PREFIX = "ENTIFY_REGISTRY"
	DB_DRIVER     = "DB_DRIVER"
	DB_USER       = "DB_USER"
	DB_PASSWORD   = "DB_PASSWORD"
	DB_HOST       = "DB_HOST"
	DB_PORT       = "DB_PORT"
	DB_SCHEMA     = "DB_SCHEMA"
	INSTALLED     = "INSTALLED"
)
